# Displaying Robot
print("Please select a left eye shape:")
eye1 = input()
print("Please select a left eye shape:")
eye2 = input()
print("           ___")
print("          |_|_|              _____")
print("          |_|_|     ____    |*_*_*|")
print(" _______   _\__\___/ __ \____|_|_   _______")
print("/ ____  |=|      \  <" + eye1 + "" + eye2 +">  /      |=|  ____ \\")
print("~|    |\|=|======\\______//======|=|/|    |~")
print(" |_   |    \      |      |      /    |    |")
print("  \==-|     \     |  2D  |     /     |----|~~/")
print("  |   |      |    |      |    |      |____/~/")
print("  |   |       \____\____/____/      /    / /")
print("  |   |         {----------}       /____/ /")
print("  |___|        /~~~~~~~~~~~~\     |_/~|_|/")
print("   \_/        |/~~~~~||~~~~~\|     /__|\\")
print("   | |         |    ||||    |     (/|| \)")
print("   | |        /     |  |     \       \\")
print("   |_|        |     |  |     |")
print("              |_____|  |_____|")
print("              (_____)  (_____)")
print("              |     |  |     |")
print("              |     |  |     |")
print("              |/~~~\|  |/~~~\|")
print("              /|___|\  /|___|\\")
print("             <_______><_______>")